/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteCosmeticsScreen` | `/CameraAgenteCosmeticsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteAlimentarScreen` | `/CameraAgenteAlimentarScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteBasicoScreen` | `/CameraAgenteBasicoScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteDataScreen` | `/CameraAgenteDataScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteStylistScreen` | `/CameraAgenteStylistScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CorAgentApp` | `/CorAgentApp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/PriceTable` | `/PriceTable`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteCosmeticsScreen` | `/CameraAgenteCosmeticsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteAlimentarScreen` | `/CameraAgenteAlimentarScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteBasicoScreen` | `/CameraAgenteBasicoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteDataScreen` | `/CameraAgenteDataScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteStylistScreen` | `/CameraAgenteStylistScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CorAgentApp` | `/CorAgentApp`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/PriceTable` | `/PriceTable`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CameraAgenteCosmeticsScreen${`?${string}` | `#${string}` | ''}` | `/CameraAgenteCosmeticsScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CameraAgenteAlimentarScreen${`?${string}` | `#${string}` | ''}` | `/CameraAgenteAlimentarScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CameraAgenteBasicoScreen${`?${string}` | `#${string}` | ''}` | `/CameraAgenteBasicoScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CameraAgenteDataScreen${`?${string}` | `#${string}` | ''}` | `/CameraAgenteDataScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CameraAgenteStylistScreen${`?${string}` | `#${string}` | ''}` | `/CameraAgenteStylistScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CorAgentApp${`?${string}` | `#${string}` | ''}` | `/CorAgentApp${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/PriceTable${`?${string}` | `#${string}` | ''}` | `/PriceTable${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteCosmeticsScreen` | `/CameraAgenteCosmeticsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteAlimentarScreen` | `/CameraAgenteAlimentarScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteBasicoScreen` | `/CameraAgenteBasicoScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteDataScreen` | `/CameraAgenteDataScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CameraAgenteStylistScreen` | `/CameraAgenteStylistScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CorAgentApp` | `/CorAgentApp`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/PriceTable` | `/PriceTable`; params?: Router.UnknownInputParams; };
    }
  }
}
